### ISSUE TITLE
Question: Does this have a simple CDN version that one can use plug n play?

### ISSUE THREAD

**Issue by Mashiane** [aarcoraci/fluid-meter#1]
Hi there

Thanks for this awesome lib. Do you happen to have a compiled CDN version that one can just use on the script tag?

Thanks

**Comment by aarcoraci** [comment]
Hey, great suggestion. I have just added a bundled version with the updated readme. You can just take the bundle.js and use it standalone on any project.

Once included it will create an object on the global scope you can use. Please take a look at the updated readme and let me know if you are having troubles.

I'll see how this can get distributed via CDNs later but for now you should be able to use it just including the file.

**Comment by aarcoraci** [comment]
Let me know if this worked so maybe we can close this issue 😄

**Comment by Mashiane** [comment]
Thank you so much. Let me give it a try.

**Comment by Mashiane** [comment]
![FluidMeter](https://user-images.githubusercontent.com/5799306/169900965-377c97be-daf3-4965-9ec2-db02e29137af.png)
I can display it but it has an error, something about t.filter

![tfilter](https://user-images.githubusercontent.com/5799306/169900997-3ccbbad0-9b81-4484-9673-a374deb8ce72.png)

**Comment by aarcoraci** [comment]
could you show me how you are importing it and calling the library ?
